spring:
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    streams:
      application-id: surge-detection-app
      bootstrap-servers: localhost:9092
      properties:

        auto.offset.reset: latest

server:
  port: 8080



